[config]

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/themes/colors.toml'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/config/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors-alpha.css'
output_path = '~/.config/waybar/colors.css'
# post_hook = 'pkill -SIGUSR2 waybar || waybar'

# [templates.eww]
# input_path = '~/.config/matugen/templates/colors.scss'
# output_path = '~/.config/eww/themes/colors.scss'
# post_hook = '[[ -n "$(eww active-windows)" ]] || systemctl restart --now --user eww-open@bar-top.service'
